- hosts: localhost
  become: true
  tasks:
  - name: general packages
    dnf: name: ['htop', 'mc', 'tmux', 'stow']

  - name: editor stuff
    dnf: name: ['emacs']

  - name: javascript development
    dnf: name: ['nvm', 'yvm']

  - name: haskell development
    dnf: name: ['stack']
