- hosts: localhost
  become: true
  tasks:
  - name: general packages
    dnf:
    - name: ['htop', 'mc', 'tmux', 'stow']
    - state: present

  - name: editor stuff
    dnf:
    - name: ['emacs']
    - state: present

  - name: javascript development
    - dnf:
      - name: ['nvm', 'yvm']
      - state: present

  - name: haskell development
    dnf:
    - name: ['stack']
    - state: present
